name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master-source
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        yarn install
        yarn build
      env:
        VUE_APP_INSTAGRAM_ACCESS_TOKEN: ${{ secrets.VUE_APP_INSTAGRAM_ACCESS_TOKEN }}
        VUE_APP_SMTP_SECURE_TOKEN: ${{ secrets.VUE_APP_SMTP_SECURE_TOKEN }}
        VUE_APP_GOOGLE_ANALYTICS_ID: ${{ secrets.VUE_APP_GOOGLE_ANALYTICS_ID }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
        COMMIT_MESSAGE: Deploying into production
        BRANCH: master
        FOLDER: dist
